.github/workflows/e2e.yaml
tests/v2.2/clusters/kind/sources.yaml
tests/v2.2/sources/helm.yaml
tests/v2.2/sources/namespace.yaml
tests/v2.2/sources/oci.yaml

Test the distribution variants against all Flux source types.

Add end-to-end test suite for Flux sources

---

.github/workflows/e2e.yaml
tests/v2.2/appliers/helm-sync.yaml
tests/v2.2/appliers/kustomize-sync.yaml
tests/v2.2/appliers/namespace.yaml
tests/v2.2/clusters/kind/appliers.yaml

Test the distribution variants against all Flux applier types.

Add end-to-end test suite for Flux appliers

---

.github/workflows/index-images.sh
.github/workflows/index-images.yaml

Scan the registry for new digests and update the images index.

Publish distribution images with digests

---

releases/release-v2.2.md

Part of: https://github.com/controlplaneio-fluxcd/distribution/issues/15

Release v2.2.3

---

README.md

This PR adds a section to introduce the guide folder and the new flux reference architecture. Once merge, we can replicate in the d1 repos.

Add an introduction paragraph to the guide section.

---

.github/workflows/e2e-fips.yaml
.github/workflows/update-images.yaml
releases/release-v2.3.md
tests/v2.3/appliers/helm-sync.yaml
tests/v2.3/appliers/kustomize-sync.yaml
tests/v2.3/appliers/namespace.yaml
tests/v2.3/clusters/kind/appliers.yaml
tests/v2.3/clusters/kind/sources.yaml
tests/v2.3/sources/helm.yaml
tests/v2.3/sources/namespace.yaml
tests/v2.3/sources/oci.yaml

Release v2.3.0

---

README.md

Add `--registry-cred` flag for providing the image pull token.

Update bootstrap procedure to Flux v2.3

---

README.md
docs/operator/flux-bootstrap-migration.md
docs/operator/flux-kustomize.md
mkdocs.yml

xref: https://github.com/controlplaneio-fluxcd/flux-operator/issues/28

Add FluxInstance kustomize examples

---

docs/marketplace/aws.md

Depends on: https://github.com/controlplaneio-fluxcd/flux-operator/pull/42 and https://github.com/controlplaneio-fluxcd/charts/pull/14

Add AWS Marketplace metering to docs

---

.github/workflows/e2e-fips.yaml

Update FIPS e2e tests to latest Kubernetes

---

docs/operator/flux-kustomize.md

Closes: https://github.com/controlplaneio-fluxcd/flux-operator/issues/92

Add SOPS decryption example to flux-operator docs

---

docs/operator/flux-sharding.md
docs/operator/fluxinstance.md
docs/operator/index.md
mkdocs.yml
rfcs/0001-flux-operator/README.md

Changelog: https://github.com/controlplaneio-fluxcd/flux-operator/releases/tag/v0.9.0

Update doc for Flux Operator v0.9

---

docs/releases/release-v2.4.md
mkdocs.yml
releases/release-v2.4.md
vex/v2.4.json

Release v2.4.0

---

tests/v2.4/appliers/helm-sync.yaml
tests/v2.4/appliers/kustomize-sync.yaml
tests/v2.4/appliers/namespace.yaml
tests/v2.4/clusters/kind/appliers.yaml
tests/v2.4/clusters/kind/sources.yaml
tests/v2.4/sources/helm.yaml
tests/v2.4/sources/namespace.yaml
tests/v2.4/sources/oci.yaml

Add tests for Flux v2.4

---

docs/operator/flux-bootstrap-migration.md

ref: https://github.com/controlplaneio-fluxcd/flux-operator/issues/108

Document how to automatically update Flux Operator

---

.github/workflows/e2e-fips.yaml
.github/workflows/e2e.yaml

Add Kubernetes 1.32.0 to the end-to-end test matrix.

Run conformance tests for Kubernetes 1.32.0

---

.github/workflows/scan-distribution.yaml

Fixes #132 
Tested here: https://github.com/controlplaneio-fluxcd/distribution/actions/runs/12319974501/job/34388241334

Add job to scan flux-operator in the Vulnerability scan workflow

---

docs/guides/flux-generic-helm-chart.md
docs/marketplace/aws.md
mkdocs.yml

Preview: https://fluxcd.control-plane.io/guides/flux-generic-helm-chart/

docs: Add Generic Helm Chart guide

---

docs/operator/flux-config.md
docs/operator/fluxinstance.md
docs/releases/release-v2.4.md
releases/release-v2.4.md

https://github.com/controlplaneio-fluxcd/flux-operator/releases/tag/v0.11.0

Update Flux Operator docs to v0.11.0

---

docs/operator/fluxinstance.md
docs/operator/monitoring.md

Update the Flux Operator docs for v0.13.0

---

docs/operator/flux-bootstrap-migration.md

xref: https://github.com/fluxcd/flux2/discussions/3671#discussioncomment-11083803

Add guide to migrate Flux Operator from Git to OCI artifacts

---

docs/operator/flux-kustomize.md

Fixes https://github.com/controlplaneio-fluxcd/flux-operator/issues/142

Add flux-operator cluster sync source verification examples

---

actions/update/action.yaml
docs/distribution/index.md
docs/distribution/install.md
docs/marketplace/aws.md
docs/operator/flux-config.md
docs/releases/release-v2.5.md
docs/theme/home.html
mkdocs.yml
releases/release-v2.5.md
tests/v2.5/appliers/helm-sync.yaml
tests/v2.5/appliers/kustomize-sync.yaml
tests/v2.5/appliers/namespace.yaml
tests/v2.5/clusters/kind/appliers.yaml
tests/v2.5/clusters/kind/sources.yaml
tests/v2.5/sources/helm.yaml
tests/v2.5/sources/namespace.yaml
tests/v2.5/sources/oci.yaml
vex/v2.5.json

Release v2.5.0

---

docs/operator/resourcesetinputprovider.md
docs/operator/resourcesets/github-pull-requests.md

Add GitHub App to ResourceSet guide

Update docs for Flux Operator v0.15.0

---

docs/operator/flux-sync.md

xref: https://github.com/controlplaneio-fluxcd/flux-operator/issues/180

docs: Sync from a Git Repository using GitHub App auth

---

docs/operator/resourcesets/github-pull-requests.md

Add GitHub Action Workflow example to docs

docs: Add GitHub Workflow to Ephemeral Environments guide

---

docs/operator/resourcesets/github-pull-requests.md

Explain how to post Flux events as comments on GitHub Pull Requests when deploying to ephemeral environments.
Thanks @matheuscscp for the GitHub dispatch idea in https://github.com/controlplaneio-fluxcd/flux-operator/issues/212

Add Status reporting on Pull Requests to docs

---

docs/operator/flux-sync.md

xref: https://github.com/fluxcd/source-controller/issues/1759

Add Azure DevOps OIDC auth example to Flux Operator docs

---

docs/operator/flux-kustomize.md

xref: https://github.com/controlplaneio-fluxcd/charts/issues/68

flux-operator: Add warning about target namespace usage

---

docs/operator/resourcesets/app-definition.md

Depends on: https://github.com/controlplaneio-fluxcd/flux-operator/pull/252
Part of: https://github.com/controlplaneio-fluxcd/flux-operator/issues/203

Add guide for decoupled ResourceSet

---

docs/llms.txt
docs/mcp/config.md
docs/operator/flux-kustomize.md

Followup: https://github.com/controlplaneio-fluxcd/flux-operator/pull/265

Add docs on how to deploy the MCP Server in Kubernetes

---

docs/guides/d2-architecture-reference.md

Link to the d2 repos for easier navigation

Add the repo list to the D2 introduction page

---

docs/releases/release-v2.6.md
releases/release-v2.6.md

Changelog: https://github.com/fluxcd/flux2/releases/tag/v2.6.4

Release v2.6.4

---

docs/operator/resourcesets/time-based-delivery.md

Add `OCIArtifactTag` RSIP example.

docs: Add OCI artifact example to schedule guide

---

docs/operator/flux-config.md
docs/operator/flux-sharding.md
docs/operator/index.md
docs/operator/install.md
docs/operator/monitoring.md
docs/theme/home.html

Add recommended reporting interval to docs

docs: Update Flux Operator monitoring guide

---

docs/operator/resourcesets/gitlab-merge-requests.md

fix typo and a little bit rephrase.

docs: Update gitlab-merge-requests.md

---

.github/workflows/e2e-fips.yaml
.github/workflows/e2e.yaml
.github/workflows/export-images.sh
.github/workflows/scan-controllers.yaml
.github/workflows/update-images.sh
.github/workflows/update-images.yaml

All workflows working pre 2.7:

ci: add support for source-watcher

---

docs/distribution/install.md
docs/llms.txt
docs/marketplace/aws.md
docs/operator/flux-bootstrap-migration.md
docs/operator/flux-config.md
docs/operator/flux-sharding.md
docs/operator/flux-sync.md
docs/releases/release-v2.7.md
mkdocs.yml
releases/release-v2.7.md
tests/v2.7/appliers/helm-sync.yaml
tests/v2.7/appliers/kustomize-sync.yaml
tests/v2.7/appliers/namespace.yaml
tests/v2.7/clusters/kind/appliers.yaml
tests/v2.7/clusters/kind/sources.yaml
tests/v2.7/sources/generators.yaml
tests/v2.7/sources/helm.yaml
tests/v2.7/sources/namespace.yaml
tests/v2.7/sources/oci.yaml
vex/v2.7.json

Part of: https://github.com/controlplaneio-fluxcd/distribution/issues/245

Release v2.7.0
