controlplaneio-fluxcd/distribution

flux-aio/README.md, flux-aio/bundles/flux-aio.cue
Add Timoni bundle to deploy [Flux AIO](https://timoni.sh/flux-aio/) with the FIPS-compliant images.
=> Enterprise Distribution for Flux AIO

.trivyignore
CVE-2019-25210 has been dismissed by the Helm team and the dry run functionality is not used in Flux.
Refs:
- https://helm.sh/blog/response-cve-2019-25210/
- https://github.com/helm/helm/issues/7275
=> Add CVE-2019-25210 to ignore list

.github/workflows/e2e-fips.yaml, .github/workflows/e2e.yaml
Changes:
- Update the Kubernetes version matrix in the FIPS tests
- Run conformance tests for Kubernetes v1.30.0 for all distros
Part of: #45
=> Run EE conformance tests for Kubernetes v1.30.0

.github/workflows/e2e-fips.yaml, releases/release-v2.2.md, releases/release-v2.3.md
Changes:
- Update test matrix with the latest Kubernetes patch releases
- Add supported Kubernetes & OpenShift versions to release notes
=> Update Kubernetes e2e test matrix

README.md, actions/update/README.md, actions/update/action.yaml
This PR adds a GitHub Action for keeping the Flux controllers images digests and manifests up-to-date with the
latest version of the Enterprise Distribution.
Using this action ensures that every time we publish new images with CVE fixes, the images digests are updated in the `flux-system` kustomization and Flux running on clusters will upgrade itself with the new images.
Example of a PR updating the Flux controllers images digests from v2.2.2 to v2.2.3
=> Add GitHub Action for automated Flux distro updates

README.md, vex/v2.2.json, vex/v2.3.json
This PR adds Vulnerability Exploitability eXchange documents for each Flux EE release in the [OpenVEX](https://github.com/openvex/spec/blob/v0.2.0/OPENVEX-SPEC.md) format.
Changes:
- Initialise VEX documents for Flux v2.2 and v2.3
- Mark CVE-2019-25210 as `not_affected` in the VEX document corresponding to Flux v2.2.x versions 
- Add a VEX section to the Supply Chain Security docs and explain how customers can use the OpenVEX docs when scanning for CVEs
Closes: #52
=> Add OpenVEX documents for Flux EE releases

.github/workflows/scan-license.yaml, README.md
Scan Flux dependencies, create a report of all licenses and check for CNCF forbidden licenses (strong copyleft and non-OSS).
=> Add license scanning

rfcs/0001-flux-operator/README.md
This RFC is for developing a Flux Operator that would manage the lifecycle of the enterprise distribution and provide a declarative API for at-scale configuration and automated upgrade of the Flux controllers.
The operator will provide the enterprise distribution with first-class support for OpenShift, Azure, AWS, GCP and other marketplaces.
Preview: https://github.com/controlplaneio-fluxcd/distribution/blob/rfc-flux-operator/rfcs/0001-flux-operator/README.md
=> [RFC-0001] Flux Operator Proposal

.trivyignore, vex/v2.3.json
Mark Alpine CVE-2024-4741, CVE-2023-42365 and CVE-2023-42364 as `vulnerable_code_not_in_execute_path`.
=> vex: Add exception for CVE-2024-4741, CVE-2023-42365, CVE-2023-42364

docs/guides/flux-policies.md, mkdocs.yml
Add guide on how to use the new `ValidatingAdmissionPolicy` API for enforce policies on multi-tenant clusters managed by Flux.
Preview: https://fluxcd.control-plane.io/guides/flux-policies/
=> Add Flux Multitenant Policies to docs

docs/operator/fluxinstance.md
The [validation spec](https://github.com/controlplaneio-fluxcd/flux-operator/blob/e916d852131d2b19b0beac180e89d5cdd36298d3/api/v1/fluxinstance_types.go#L165) declared for the operator declares these using the cloud vendor names rather than the k8s implementation names.
=> Update cluster type documentation to reflect schema

.github/workflows/e2e.yaml
Add `ubuntu-24.04-arm` runners to the Flux Enterprise conformance tests matrix.
Ref: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> Run conformance tests for ARM Kubernetes clusters

.github/workflows/scan-alpine.yaml, .github/workflows/scan-controllers.yaml, .github/workflows/scan-distroless.yaml, .github/workflows/scan-operator.yaml, README.md
For some reason I couldn't find, the job URL for notifying Zulip is only found if we run the logic in a top-level job (rather than inside a reusable workflow like before).
Now we can have separate `Vulnerability scan - ${thing}` workflows, which is better because we don't show a big red failed status if only one of those fail e.g. if alpine fails we still wan't to give distroless customers peace of mind.
=> Split Vulnerability scan into one workflow for alpine, one for distroless and one for operator, and fix Zulip integration

docs/operator/resourcesets/gitlab-merge-requests.md
Hi, 
This one fix documentation for gitlab-merge-requests page.
I just replace GitHub by GitLab. And PR by MR.
=> docs: Fix typo in GitLab MR guide

actions/push/README.md, actions/push/action.yaml
Introduce a GitHub Action for making it easier to push OCI artifacts with the `flux` CLI.
Tested here: https://github.com/matheuscscp/d1-fleet/actions/workflows/test-push.yaml
Closes #167
=> Add push GitHub Action for pushing Flux OCI artifacts

.trivyignore, vex/v2.5.json
Mark Alpine CVE-2025-29087 as `vulnerable_code_not_in_execute_path`.
=> vex: Add exception for CVE-2025-29087

.github/workflows/e2e-fips.yaml, .github/workflows/e2e.yaml, docs/releases/release-v2.5.md, releases/release-v2.5.md
Add Kubernetes v1.33.0 to the end-to-end test matrix.
Add Kubernetes 1.33 and OpenShift 4.18 to the Flux Enterprise supported versions.
=> Run conformance tests for Kubernetes 1.33.0

.trivyignore, vex/v2.6.json
Mark Helm CVE-2025-53547 as `vulnerable_code_not_in_execute_path` ([OpenVEX Specification v0.2.0](https://github.com/openvex/spec/blob/main/OPENVEX-SPEC.md)).
The affected code is not executed by Flux:
- The source-controller implements a custom Helm chart downloader that does not use the vulnerable code path in Helm SDK. 
- The helm-controller does not downloads Helm charts, and the vulnerable code path in Helm SDK is not used.
Scanner usage example:
```
trivy image ghcr.io/controlplaneio-fluxcd/distroless/source-controller:v1.6.2 --vex ./vex/v2.6.json --show-suppressed
trivy image ghcr.io/controlplaneio-fluxcd/distroless/helm-controller:v1.3.0 --vex ./vex/v2.6.json --show-suppressed
```
=> vex: Add exception for CVE-2025-53547

docs/operator/resourcesets/image-automation.md, mkdocs.yml
Add guide to demonstrate how to use the Flux Operator APIs as an alternative to the Flux Image Automation controllers.
=> docs: Using ResourceSets for Image Update Automation

actions/push/README.md, actions/push/action.yaml
This PR allows specifying a provider input for the `--provider` flag available in the `flux * artifact` commands used internally by the `push` action.
I have tested this with CP's internal infrastructure and it works when the `setup` action is used `with: {version: v2.6.4}`, but we should wait until Flux 2.7.1 is released to merge this PR (https://github.com/fluxcd/flux2/pull/5551 will be released in Flux 2.7.1).
=> actions/push: introduce provider input

docs/distribution/install.md, docs/distribution/upgrade.md, mkdocs.yml
Add upgrade procedure for Flux Operator and the Flux distribution.
=> Add upgrade procedure to Flux Operator docs
